import fs from "fs";
import path from "path";


const collegesData = [
  {
    name: "Indian Institute of Technology Madras (IITM)",
    slug: "iit-madras",
    city: "Chennai",
    district: "Chennai",
    state: "Tamil Nadu",
    address: "IIT Madras, Adyar, Chennai, Tamil Nadu 600036",
    collegeType: "Engineering",
    ownership: "Government",
    university: "IIT Madras (Autonomous)",
    rating: 4.9,
    reviewCount: 342,
    annualFees: 220000,
    averagePackage: 21.4,
    highestPackage: 66.0,
    placementRate: 98.0,
    popularCourse: "Computer Science",
    description: "IIT Madras is a prestigious public technical university located in Chennai, Tamil Nadu, India. As one of the Indian Institutes of Technology, it is recognized as an Institute of National Importance and has consistently ranked as the top engineering institute in India.",
    logo: "https://images.unsplash.com/photo-1562774053-701939374585?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "https://www.iitm.ac.in"
  },
  {
    name: "Anna University (CEG Campus)",
    slug: "anna-university",
    city: "Chennai",
    district: "Chennai",
    state: "Tamil Nadu",
    address: "Sardar Patel Road, Guindy, Chennai, Tamil Nadu 600025",
    collegeType: "Engineering",
    ownership: "Government",
    university: "Anna University",
    rating: 4.3,
    reviewCount: 160,
    annualFees: 48000,
    averagePackage: 8.5,
    highestPackage: 40.0,
    placementRate: 91.0,
    popularCourse: "Computer Science",
    description: "The College of Engineering, Guindy (CEG) in Chennai is India's oldest engineering college, established in 1794. It serves as the main campus of Anna University, offering highly affordable and prestigious degrees.",
    logo: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "https://www.annauniv.edu"
  },
  {
    name: "PSG College of Technology",
    slug: "psg-college-of-technology",
    city: "Coimbatore",
    district: "Coimbatore",
    state: "Tamil Nadu",
    address: "Avinashi Road, Peelamedu, Coimbatore, Tamil Nadu 641004",
    collegeType: "Engineering",
    ownership: "Government Aided",
    university: "Anna University",
    rating: 4.4,
    reviewCount: 220,
    annualFees: 150000,
    averagePackage: 10.1,
    highestPackage: 44.0,
    placementRate: 94.0,
    popularCourse: "Mechanical",
    description: "PSG College of Technology is a government-aided autonomous engineering college in Coimbatore, India. Established in 1951, it is highly regarded for its close ties with local industries and excellent placement rates for core engineering disciplines.",
    logo: "https://images.unsplash.com/photo-1562774053-701939374585?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "https://www.psgtech.edu"
  },
  {
    name: "Coimbatore Institute of Technology",
    slug: "coimbatore-institute-of-technology",
    city: "Coimbatore",
    district: "Coimbatore",
    state: "Tamil Nadu",
    address: "Civil Aerodrome Post, Coimbatore, Tamil Nadu 641014",
    collegeType: "Engineering",
    ownership: "Government Aided",
    university: "Anna University",
    rating: 4.0,
    reviewCount: 95,
    annualFees: 125000,
    averagePackage: 6.8,
    highestPackage: 30.0,
    placementRate: 86.0,
    popularCourse: "Mechanical",
    description: "Coimbatore Institute of Technology is a government-aided autonomous engineering college located in Coimbatore, Tamil Nadu, India. Established in 1956, CIT offers top-notch engineering curricula with high focus on mechanical and chemical engineering sciences.",
    logo: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "https://www.cit.edu.in"
  },
  {
    name: "Thiagarajar College of Engineering",
    slug: "thiagarajar-college-of-engineering",
    city: "Madurai",
    district: "Madurai",
    state: "Tamil Nadu",
    address: "Tirupparankundram, Madurai, Tamil Nadu 625015",
    collegeType: "Engineering",
    ownership: "Government Aided",
    university: "Anna University",
    rating: 4.3,
    reviewCount: 135,
    annualFees: 110000,
    averagePackage: 7.8,
    highestPackage: 32.0,
    placementRate: 89.0,
    popularCourse: "Electrical",
    description: "Thiagarajar College of Engineering is a government-aided, autonomous institution located in Madurai, Tamil Nadu. It is one of the premier institutions in southern Tamil Nadu, with excellent placements in IT and manufacturing fields.",
    logo: "https://images.unsplash.com/photo-1562774053-701939374585?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "https://www.tce.edu"
  },
  {
    name: "Government College of Technology",
    slug: "government-college-of-technology",
    city: "Coimbatore",
    district: "Coimbatore",
    state: "Tamil Nadu",
    address: "Thadagam Road, Coimbatore, Tamil Nadu 641013",
    collegeType: "Engineering",
    ownership: "Government",
    university: "Anna University",
    rating: 4.1,
    reviewCount: 110,
    annualFees: 35000,
    averagePackage: 6.2,
    highestPackage: 24.0,
    placementRate: 85.0,
    popularCourse: "Civil",
    description: "Government College of Technology, Coimbatore is a state-funded autonomous engineering college. It offers highly affordable engineering programs and has a rich heritage of academic brilliance.",
    logo: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "https://www.gct.ac.in"
  },
  {
    name: "SRM Institute of Science and Technology",
    slug: "srm-institute-of-science-and-technology",
    city: "Chennai",
    district: "Chengalpattu",
    state: "Tamil Nadu",
    address: "SRM Nagar, Kattankulathur, Tamil Nadu 603203",
    collegeType: "Engineering",
    ownership: "Private",
    university: "SRM Deemed University",
    rating: 4.0,
    reviewCount: 420,
    annualFees: 260000,
    averagePackage: 7.5,
    highestPackage: 45.0,
    placementRate: 90.0,
    popularCourse: "Computer Science",
    description: "SRM Institute of Science and Technology is a top-tier private deemed university. The massive Kattankulathur campus offers advanced research labs, international collaborations, and recruitment drives by global giants.",
    logo: "https://images.unsplash.com/photo-1562774053-701939374585?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "https://www.srmist.edu.in"
  },
  {
    name: "VIT University Vellore",
    slug: "vit-vellore",
    city: "Vellore",
    district: "Vellore",
    state: "Tamil Nadu",
    address: "Katpadi, Vellore, Tamil Nadu 632014",
    collegeType: "Engineering",
    ownership: "Private",
    university: "VIT Deemed University",
    rating: 4.2,
    reviewCount: 480,
    annualFees: 198000,
    averagePackage: 9.2,
    highestPackage: 44.0,
    placementRate: 93.0,
    popularCourse: "Computer Science",
    description: "Vellore Institute of Technology is a leading private research deemed university. It features a flexible credit system (FFCS) and hosts massive recruitment drives, securing international records.",
    logo: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "https://vit.ac.in"
  },
  {
    name: "SSN College of Engineering",
    slug: "ssn-college-of-engineering",
    city: "Chennai",
    district: "Kancheepuram",
    state: "Tamil Nadu",
    address: "Old Mahabalipuram Road, Kalavakkam, Tamil Nadu 603110",
    collegeType: "Engineering",
    ownership: "Private",
    university: "Anna University",
    rating: 4.5,
    reviewCount: 195,
    annualFees: 120000,
    averagePackage: 11.5,
    highestPackage: 48.0,
    placementRate: 95.0,
    popularCourse: "Computer Science",
    description: "Sri Sivasubramaniya Nadar (SSN) College of Engineering, founded by Dr. Shiv Nadar, is a premier private engineering college on OMR, Chennai. It is famous for academic excellence, sports, and research funding.",
    logo: "https://images.unsplash.com/photo-1562774053-701939374585?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "https://www.ssn.edu.in"
  },
  {
    name: "SASTRA Deemed University",
    slug: "sastra-deemed-university",
    city: "Thanjavur",
    district: "Thanjavur",
    state: "Tamil Nadu",
    address: "Tirumalaisamudram, Thanjavur, Tamil Nadu 613401",
    collegeType: "Engineering",
    ownership: "Private",
    university: "SASTRA Deemed University",
    rating: 4.3,
    reviewCount: 205,
    annualFees: 165000,
    averagePackage: 8.8,
    highestPackage: 38.0,
    placementRate: 91.0,
    popularCourse: "Computer Science",
    description: "SASTRA University is a renowned private deemed university in Thanjavur. It has been awarded Category-1 status by UGC and has strong research output in engineering, law, sciences, and humanities.",
    logo: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "https://www.sastra.edu"
  },
  {
    name: "Kumaraguru College of Technology",
    slug: "kumaraguru-college-of-technology",
    city: "Coimbatore",
    district: "Coimbatore",
    state: "Tamil Nadu",
    address: "Athipalayam Road, Chinnavedampatti, Coimbatore, Tamil Nadu 641049",
    collegeType: "Engineering",
    ownership: "Private",
    university: "Anna University",
    rating: 4.2,
    reviewCount: 180,
    annualFees: 140000,
    averagePackage: 7.2,
    highestPackage: 28.0,
    placementRate: 88.0,
    popularCourse: "Computer Science",
    description: "Kumaraguru College of Technology is a prominent private autonomous engineering college in Coimbatore. Part of the Sakthi Group, KCT provides high-quality technical education, robust labs, and incubator startups setups.",
    logo: "https://images.unsplash.com/photo-1562774053-701939374585?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "https://www.kct.ac.in"
  },
  {
    name: "Chennai Institute of Technology",
    slug: "chennai-institute-of-technology",
    city: "Chennai",
    district: "Kancheepuram",
    state: "Tamil Nadu",
    address: "Sarathy Nagar, Kundrathur, Chennai, Tamil Nadu 600069",
    collegeType: "Engineering",
    ownership: "Private",
    university: "Anna University",
    rating: 4.4,
    reviewCount: 155,
    annualFees: 110000,
    averagePackage: 8.9,
    highestPackage: 44.0,
    placementRate: 94.0,
    popularCourse: "Computer Science",
    description: "Chennai Institute of Technology (CIT) is a fast-growing private engineering college in Chennai. Known for industrial collaborations, skill development centers, and exceptional placements in product design and core domains.",
    logo: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "https://www.citchennai.edu.in"
  },
  // Additional Tamil Nadu Colleges to demo pagination and filters
  {
    name: "Loyola College Chennai",
    slug: "loyola-college-chennai",
    city: "Chennai",
    district: "Chennai",
    state: "Tamil Nadu",
    address: "Sterling Road, Nungambakkam, Chennai, Tamil Nadu 600034",
    collegeType: "Arts & Science",
    ownership: "Private",
    university: "University of Madras",
    rating: 4.6,
    reviewCount: 290,
    annualFees: 45000,
    averagePackage: 5.4,
    highestPackage: 15.0,
    placementRate: 85.0,
    popularCourse: "Arts & Science",
    description: "Loyola College is a prestigious private Catholic higher education institution run by the Society of Jesus in Chennai. It consistently ranks among the top 5 colleges in India for arts, science, and commerce.",
    logo: "https://images.unsplash.com/photo-1562774053-701939374585?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "https://www.loyolacollege.edu"
  },
  {
    name: "Madras Christian College (MCC)",
    slug: "madras-christian-college",
    city: "Chennai",
    district: "Chennai",
    state: "Tamil Nadu",
    address: "Tambaram East, Chennai, Tamil Nadu 600059",
    collegeType: "Arts & Science",
    ownership: "Government Aided",
    university: "University of Madras",
    rating: 4.5,
    reviewCount: 240,
    annualFees: 38000,
    averagePackage: 4.8,
    highestPackage: 12.0,
    placementRate: 82.0,
    popularCourse: "Arts & Science",
    description: "Madras Christian College is a liberal arts and sciences college in Chennai. Established in 1837, its vast scrub-jungle campus is highly regarded for academic freedom, rich student culture, and notable alumni.",
    logo: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "https://mcc.edu.in"
  },
  {
    name: "PSG College of Arts and Science",
    slug: "psg-college-of-arts-and-science",
    city: "Coimbatore",
    district: "Coimbatore",
    state: "Tamil Nadu",
    address: "Peelamedu, Coimbatore, Tamil Nadu 641014",
    collegeType: "Arts & Science",
    ownership: "Government Aided",
    university: "Bharathiar University",
    rating: 4.4,
    reviewCount: 175,
    annualFees: 40000,
    averagePackage: 4.6,
    highestPackage: 11.0,
    placementRate: 80.0,
    popularCourse: "Arts & Science",
    description: "PSG College of Arts and Science is an autonomous college in Coimbatore. Established in 1947, it offers state-of-the-art arts, science, and computer applications programs with massive industry linkages.",
    logo: "https://images.unsplash.com/photo-1562774053-701939374585?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "https://www.psgcas.ac.in"
  },
  {
    name: "Madras Medical College (MMC)",
    slug: "madras-medical-college",
    city: "Chennai",
    district: "Chennai",
    state: "Tamil Nadu",
    address: "Near Central Railway Station, Park Town, Chennai, Tamil Nadu 600003",
    collegeType: "Medical",
    ownership: "Government",
    university: "The Tamil Nadu Dr. M.G.R. Medical University",
    rating: 4.8,
    reviewCount: 150,
    annualFees: 18000,
    averagePackage: 12.0,
    highestPackage: 30.0,
    placementRate: 99.0,
    popularCourse: "Medical",
    description: "Madras Medical College, established in 1835, is one of the oldest medical colleges in Asia. It is the premier state-funded medical school in Tamil Nadu, operating the major Rajiv Gandhi Government General Hospital.",
    logo: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "https://www.mmc.ac.in"
  },
  {
    name: "Christian Medical College Vellore (CMC)",
    slug: "christian-medical-college-vellore",
    city: "Vellore",
    district: "Vellore",
    state: "Tamil Nadu",
    address: "Ida Scudder Road, Vellore, Tamil Nadu 632004",
    collegeType: "Medical",
    ownership: "Private",
    university: "The Tamil Nadu Dr. M.G.R. Medical University",
    rating: 4.9,
    reviewCount: 310,
    annualFees: 52000,
    averagePackage: 15.0,
    highestPackage: 36.0,
    placementRate: 100.0,
    popularCourse: "Medical",
    description: "Christian Medical College Vellore is an internationally renowned medical school and hospital. CMC Vellore has pioneered many medical breakthroughs in India and is top-ranked for research and clinical care.",
    logo: "https://images.unsplash.com/photo-1562774053-701939374585?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "https://www.cmcvellore.ac.in"
  },
  {
    name: "Great Lakes Institute of Management",
    slug: "great-lakes-institute-of-management",
    city: "Chennai",
    district: "Chengalpattu",
    state: "Tamil Nadu",
    address: "East Coast Road, Manamai, Tamil Nadu 603102",
    collegeType: "Management",
    ownership: "Private",
    university: "Great Lakes (Autonomous)",
    rating: 4.4,
    reviewCount: 165,
    annualFees: 450000,
    averagePackage: 14.5,
    highestPackage: 34.0,
    placementRate: 98.0,
    popularCourse: "Management",
    description: "Great Lakes Institute of Management is a premier private business school on the scenic ECR near Chennai. Founded by Dr. Bala V. Balachandran, it offers world-class one-year MBA programs.",
    logo: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "https://www.greatlakes.edu.in/chennai"
  },
  {
    name: "Government College of Engineering Salem",
    slug: "government-college-of-engineering-salem",
    city: "Salem",
    district: "Salem",
    state: "Tamil Nadu",
    address: "NH-44, Salem, Tamil Nadu 636011",
    collegeType: "Engineering",
    ownership: "Government",
    university: "Anna University",
    rating: 3.9,
    reviewCount: 78,
    annualFees: 30000,
    averagePackage: 5.5,
    highestPackage: 18.0,
    placementRate: 82.0,
    popularCourse: "Electrical",
    description: "Government College of Engineering, Salem is a third state-funded engineering institution established in 1966. It serves the western industrial belt of Tamil Nadu with strong core department structures.",
    logo: "https://images.unsplash.com/photo-1562774053-701939374585?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "https://www.gcesalem.edu.in"
  },
  {
    name: "Government College of Engineering Srirangam",
    slug: "government-college-of-engineering-srirangam",
    city: "Trichy",
    district: "Tiruchirappalli",
    state: "Tamil Nadu",
    address: "Sethurapatti, Tiruchirappalli, Tamil Nadu 620012",
    collegeType: "Engineering",
    ownership: "Government",
    university: "Anna University",
    rating: 3.8,
    reviewCount: 45,
    annualFees: 32000,
    averagePackage: 4.8,
    highestPackage: 12.0,
    placementRate: 78.0,
    popularCourse: "Computer Science",
    description: "Government College of Engineering Srirangam is a state government engineering college located in Trichy. Established in 2013, it provides modern infrastructure and affordable engineering programs.",
    logo: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "https://gces.edu.in"
  },
  {
    name: "Government College of Engineering Tirunelveli",
    slug: "government-college-of-engineering-tirunelveli",
    city: "Tirunelveli",
    district: "Tirunelveli",
    state: "Tamil Nadu",
    address: "NH-7, Tirunelveli, Tamil Nadu 627007",
    collegeType: "Engineering",
    ownership: "Government",
    university: "Anna University",
    rating: 4.0,
    reviewCount: 65,
    annualFees: 31000,
    averagePackage: 5.2,
    highestPackage: 16.0,
    placementRate: 80.0,
    popularCourse: "Civil",
    description: "Government College of Engineering, Tirunelveli is a state-funded institution in southern Tamil Nadu, established in 1981. It offers highly subsidized fees and has strong academic records in core fields.",
    logo: "https://images.unsplash.com/photo-1562774053-701939374585?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "https://www.gcetly.ac.in"
  },
  {
    name: "Thiagarajar School of Management (TSM)",
    slug: "thiagarajar-school-of-management",
    city: "Madurai",
    district: "Madurai",
    state: "Tamil Nadu",
    address: "Pamban Swamy Nagar, Thirupparankundram, Madurai, Tamil Nadu 625005",
    collegeType: "Management",
    ownership: "Private",
    university: "Madurai Kamaraj University",
    rating: 4.2,
    reviewCount: 88,
    annualFees: 320000,
    averagePackage: 6.9,
    highestPackage: 18.0,
    placementRate: 92.0,
    popularCourse: "Management",
    description: "Thiagarajar School of Management is a premier management institute located in Madurai, Tamil Nadu. Established in 1962, it offers MBA and PGDM programs known for strong core placements and academic excellence.",
    logo: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "https://tsm.ac.in"
  },
  {
    name: "Department of Management Studies Anna University (DoMS)",
    slug: "doms-anna-university",
    city: "Chennai",
    district: "Chennai",
    state: "Tamil Nadu",
    address: "Anna University, Sardar Patel Road, Chennai, Tamil Nadu 600025",
    collegeType: "Management",
    ownership: "Government",
    university: "Anna University",
    rating: 4.3,
    reviewCount: 92,
    annualFees: 80000,
    averagePackage: 7.2,
    highestPackage: 21.0,
    placementRate: 90.0,
    popularCourse: "Management",
    description: "Department of Management Studies (DoMS) is a business school inside the Anna University campus. Known for quality MBA education, low government fee structure, and excellent campus placements in corporate firms.",
    logo: "https://images.unsplash.com/photo-1562774053-701939374585?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "https://www.domsau.org"
  },
  {
    name: "Bannari Amman Institute of Technology (BIT)",
    slug: "bannari-amman-institute-of-technology",
    city: "Coimbatore",
    district: "Erode",
    state: "Tamil Nadu",
    address: "Alathukombai Post, Sathyamangalam, Erode, Tamil Nadu 638401",
    collegeType: "Engineering",
    ownership: "Private",
    university: "Anna University",
    rating: 4.1,
    reviewCount: 165,
    annualFees: 135000,
    averagePackage: 6.8,
    highestPackage: 22.0,
    placementRate: 88.0,
    popularCourse: "Computer Science",
    description: "Bannari Amman Institute of Technology is an autonomous private engineering college located in Sathyamangalam near Coimbatore. It features top-notch green infrastructure and massive computer-lab resources.",
    logo: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "https://www.bitsathy.ac.in"
  },
  {
    name: "Kongu Engineering College (KEC)",
    slug: "kongu-engineering-college",
    city: "Salem",
    district: "Erode",
    state: "Tamil Nadu",
    address: "Perundurai, Erode, Tamil Nadu 638060",
    collegeType: "Engineering",
    ownership: "Private",
    university: "Anna University",
    rating: 4.1,
    reviewCount: 140,
    annualFees: 130000,
    averagePackage: 6.5,
    highestPackage: 20.0,
    placementRate: 87.0,
    popularCourse: "Electrical",
    description: "Kongu Engineering College is an autonomous private engineering college in Erode district, serving the Salem and Coimbatore regions. Known for academic excellence, technical symposiums, and core job recruitments.",
    logo: "https://images.unsplash.com/photo-1562774053-701939374585?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "https://www.kongu.ac.in"
  },
  {
    name: "St. Joseph's College of Engineering",
    slug: "st-josephs-college-of-engineering",
    city: "Chennai",
    district: "Chennai",
    state: "Tamil Nadu",
    address: "Old Mahabalipuram Road, Sholinganallur, Chennai, Tamil Nadu 600119",
    collegeType: "Engineering",
    ownership: "Private",
    university: "Anna University",
    rating: 4.0,
    reviewCount: 145,
    annualFees: 125000,
    averagePackage: 6.2,
    highestPackage: 18.0,
    placementRate: 85.0,
    popularCourse: "Computer Science",
    description: "St. Joseph's College of Engineering is a prominent private autonomous engineering college in Chennai. Known for academic discipline, student welfare activities, and consistent placements in software development firms.",
    logo: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "https://stjosephs.ac.in"
  },
  {
    name: "PSG College of Arts and Science (Self-Financed)",
    slug: "psg-college-of-arts-and-science-sf",
    city: "Coimbatore",
    district: "Coimbatore",
    state: "Tamil Nadu",
    address: "Peelamedu, Coimbatore, Tamil Nadu 641014",
    collegeType: "Arts & Science",
    ownership: "Private",
    university: "Bharathiar University",
    rating: 4.2,
    reviewCount: 88,
    annualFees: 75000,
    averagePackage: 4.8,
    highestPackage: 10.0,
    placementRate: 82.0,
    popularCourse: "Arts & Science",
    description: "PSG College of Arts and Science Self-Financed section offers premium science and management courses with highly modern computational tools and training.",
    logo: "https://images.unsplash.com/photo-1562774053-701939374585?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "https://www.psgcas.ac.in"
  },
  {
    name: "College of Nursing, Christian Medical College, Vellore",
    slug: "college-of-nursing-christian-medical-college-vellore",
    city: "Vellore",
    district: "Vellore",
    state: "Tamil Nadu",
    address: "Kagithapattarai Campus, Ida Scudder Road, Vellore – 632004, Tamil Nadu, India",
    collegeType: "Nursing College",
    ownership: "Private",
    university: "The Tamil Nadu Dr. M.G.R. Medical University, Chennai",
    rating: 4.6,
    reviewCount: 96,
    annualFees: 100000,
    averagePackage: 7.5,
    highestPackage: 14.0,
    placementRate: 90,
    popularCourse: "B.Sc. Nursing",
    description: "College of Nursing, Christian Medical College, Vellore provides professional nursing education combining classroom learning, laboratory training and extensive clinical experience. The nursing campus is located at Kagithapattarai in Vellore and is closely integrated with the clinical environment of CMC.",
    logo: "/assets/cmc-vellore-college-of-nursing.jpg",
    coverImage: "/assets/cmc-vellore-college-of-nursing.jpg",
    officialWebsite: "https://www.cmcvellore.edu.in/college-of-nursing/"
  },
  {
    name: "Stanley Medical College",
    slug: "stanley-medical-college",
    city: "Chennai",
    district: "Chennai",
    state: "Tamil Nadu",
    address: "M.C. Road, Old Washermanpet, Chennai – 600001, Tamil Nadu, India",
    collegeType: "Medical",
    ownership: "Government",
    university: "The Tamil Nadu Dr. M.G.R. Medical University, Chennai",
    rating: 4.7,
    reviewCount: 110,
    annualFees: 18000,
    averagePackage: 11.5,
    highestPackage: 22,
    placementRate: 94,
    popularCourse: "MBBS",
    description: "Stanley Medical College is a renowned government medical institution in Chennai. Known for its historical building and the famous Stanley Hospital, it provides excellent clinical training and research opportunities in various disciplines.",
    logo: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "http://www.stanleymedicalcollege.ac.in"
  },
  {
    name: "Kilpauk Medical College",
    slug: "kilpauk-medical-college",
    city: "Chennai",
    district: "Chennai",
    state: "Tamil Nadu",
    address: "825, Poonamallee High Rd, Kilpauk, Chennai – 600010, Tamil Nadu, India",
    collegeType: "Medical",
    ownership: "Government",
    university: "The Tamil Nadu Dr. M.G.R. Medical University, Chennai",
    rating: 4.5,
    reviewCount: 95,
    annualFees: 18000,
    averagePackage: 10.5,
    highestPackage: 20,
    placementRate: 92,
    popularCourse: "MBBS",
    description: "Government Kilpauk Medical College is a well-established state medical institute in Chennai. It offers professional undergraduate and postgraduate courses in medicine and surgery with top-tier clinical postings.",
    logo: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "http://www.gkmc.in"
  },
  {
    name: "ESIC Medical College & PGIMSR",
    slug: "esic-medical-college-pgimsr",
    city: "Chennai",
    district: "Chennai",
    state: "Tamil Nadu",
    address: "Ashok Pillar Rd, KK Nagar, Chennai – 600078, Tamil Nadu, India",
    collegeType: "Medical",
    ownership: "Government",
    university: "The Tamil Nadu Dr. M.G.R. Medical University, Chennai",
    rating: 4.4,
    reviewCount: 78,
    annualFees: 100000,
    averagePackage: 9.8,
    highestPackage: 18,
    placementRate: 91,
    popularCourse: "MBBS",
    description: "ESIC Medical College & PGIMSR, Chennai is a co-educational medical school run by the Employees' State Insurance Corporation. It provides state-of-the-art laboratory infrastructure and clinical experience in its general hospital.",
    logo: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "https://www.esic.gov.in"
  },
  {
    name: "Government Medical College, Omandurar",
    slug: "government-medical-college-omandurar",
    city: "Chennai",
    district: "Chennai",
    state: "Tamil Nadu",
    address: "Omandurar Government Estate, Anna Salai, Chennai – 600002, Tamil Nadu, India",
    collegeType: "Medical",
    ownership: "Government",
    university: "The Tamil Nadu Dr. M.G.R. Medical University, Chennai",
    rating: 4.6,
    reviewCount: 64,
    annualFees: 18000,
    averagePackage: 10.2,
    highestPackage: 19.5,
    placementRate: 93,
    popularCourse: "MBBS",
    description: "Government Medical College, Omandurar Government Estate is a newly built public medical college in Chennai. It offers state-of-the-art diagnostics and tertiary care facilities to medical students and patients.",
    logo: "https://images.unsplash.com/photo-1562774053-701939374585?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "http://www.gmcogep.org"
  },
  {
    name: "Madha Medical College and Hospital",
    slug: "madha-medical-college-and-hospital",
    city: "Chennai",
    district: "Chennai",
    state: "Tamil Nadu",
    address: "Kundrathur Main Road, Kovur, Chennai – 600122, Tamil Nadu, India",
    collegeType: "Medical",
    ownership: "Private",
    university: "The Tamil Nadu Dr. M.G.R. Medical University, Chennai",
    rating: 4.1,
    reviewCount: 52,
    annualFees: 450000,
    averagePackage: 8,
    highestPackage: 15,
    placementRate: 88,
    popularCourse: "MBBS",
    description: "Madha Medical College and Hospital is a private self-financing medical college. It offers quality medical education alongside extensive outreach and community health camps in the suburban areas of Chennai.",
    logo: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "http://www.madhamedicalcollege.org"
  },
  {
    name: "Panimalar Medical College Hospital & Research Institute",
    slug: "panimalar-medical-college-hospital-research-institute",
    city: "Chennai",
    district: "Chennai",
    state: "Tamil Nadu",
    address: "Bangalore Trunk Road, Varadharajapuram, Poonamallee, Chennai – 600123, Tamil Nadu, India",
    collegeType: "Medical",
    ownership: "Private",
    university: "The Tamil Nadu Dr. M.G.R. Medical University, Chennai",
    rating: 4.3,
    reviewCount: 71,
    annualFees: 400000,
    averagePackage: 8.5,
    highestPackage: 16,
    placementRate: 89,
    popularCourse: "MBBS",
    description: "Panimalar Medical College Hospital & Research Institute is a private Christian minority medical institution. Part of the Panimalar group, it features advanced simulation laboratories, classrooms, and a multi-specialty research hospital.",
    logo: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "https://pmchri.ac.in"
  },
  {
    name: "Tagore Medical College & Hospital",
    slug: "tagore-medical-college-hospital",
    city: "Chennai",
    district: "Chengalpattu",
    state: "Tamil Nadu",
    address: "Rathinamangalam, Vandalur Post, Chennai – 600127, Tamil Nadu, India",
    collegeType: "Medical",
    ownership: "Private",
    university: "The Tamil Nadu Dr. M.G.R. Medical University, Chennai",
    rating: 4,
    reviewCount: 48,
    annualFees: 385000,
    averagePackage: 7.8,
    highestPackage: 14.5,
    placementRate: 87,
    popularCourse: "MBBS",
    description: "Tagore Medical College & Hospital is a private self-financing medical college. Set in a green campus near Vandalur, it focuses on clinical practice, modern medical technologies, and professional patient ethics.",
    logo: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "http://tagoremch.edu.in"
  },
  {
    name: "Sri Muthukumaran Medical College Hospital & Research Institute",
    slug: "sri-muthukumaran-medical-college-hospital-research-institute",
    city: "Chennai",
    district: "Kanchipuram",
    state: "Tamil Nadu",
    address: "Chikkarayapuram, Near Kovur, Chennai – 600069, Tamil Nadu, India",
    collegeType: "Medical",
    ownership: "Private",
    university: "The Tamil Nadu Dr. M.G.R. Medical University, Chennai",
    rating: 3.9,
    reviewCount: 37,
    annualFees: 390000,
    averagePackage: 7.2,
    highestPackage: 13.8,
    placementRate: 85,
    popularCourse: "MBBS",
    description: "Sri Muthukumaran Medical College Hospital & Research Institute is a private, self-financing medical institution in Kanchipuram district. It serves a large rural and suburban population, offering excellent field experience to students.",
    logo: "https://images.unsplash.com/photo-1562774053-701939374585?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "http://smmchri.res.in"
  },
  {
    name: "Madurai Medical College",
    slug: "madurai-medical-college",
    city: "Madurai",
    district: "Madurai",
    state: "Tamil Nadu",
    address: "Panagal Road, Madurai – 625020, Tamil Nadu, India",
    collegeType: "Medical",
    ownership: "Government",
    university: "The Tamil Nadu Dr. M.G.R. Medical University, Chennai",
    rating: 4.6,
    reviewCount: 92,
    annualFees: 18000,
    averagePackage: 10.8,
    highestPackage: 21,
    placementRate: 93,
    popularCourse: "MBBS",
    description: "Madurai Medical College is an esteemed government medical college established in 1954. It provides top medical education and handles high volume tertiary care cases through the Government Rajaji Hospital.",
    logo: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "http://www.mdumc.edu.in"
  },
  {
    name: "Coimbatore Medical College",
    slug: "coimbatore-medical-college",
    city: "Coimbatore",
    district: "Coimbatore",
    state: "Tamil Nadu",
    address: "Avinashi Road, Civil Aerodrome Post, Coimbatore – 641014, Tamil Nadu, India",
    collegeType: "Medical",
    ownership: "Government",
    university: "The Tamil Nadu Dr. M.G.R. Medical University, Chennai",
    rating: 4.7,
    reviewCount: 98,
    annualFees: 18000,
    averagePackage: 11.2,
    highestPackage: 21.5,
    placementRate: 94,
    popularCourse: "MBBS",
    description: "Coimbatore Medical College is a premier state government-run medical institution. Established in 1966, it is situated on Avinashi Road and works closely with the Coimbatore Government Hospital.",
    logo: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "http://www.coimbatoremedicalcollege.ac.in"
  },
  {
    name: "Tirunelveli Medical College",
    slug: "tirunelveli-medical-college",
    city: "Tirunelveli",
    district: "Tirunelveli",
    state: "Tamil Nadu",
    address: "Palayamkottai, Tirunelveli – 627011, Tamil Nadu, India",
    collegeType: "Medical",
    ownership: "Government",
    university: "The Tamil Nadu Dr. M.G.R. Medical University, Chennai",
    rating: 4.5,
    reviewCount: 77,
    annualFees: 18000,
    averagePackage: 10,
    highestPackage: 19,
    placementRate: 92,
    popularCourse: "MBBS",
    description: "Tirunelveli Medical College is a prominent government medical institution in Palayamkottai, Tirunelveli. Famously known as TVMC, it offers comprehensive clinical experience in southern districts of Tamil Nadu.",
    logo: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "http://www.tvmc.ac.in"
  },
  {
    name: "Thanjavur Medical College",
    slug: "thanjavur-medical-college",
    city: "Thanjavur",
    district: "Thanjavur",
    state: "Tamil Nadu",
    address: "Medical College Road, Thanjavur – 613004, Tamil Nadu, India",
    collegeType: "Medical",
    ownership: "Government",
    university: "The Tamil Nadu Dr. M.G.R. Medical University, Chennai",
    rating: 4.6,
    reviewCount: 81,
    annualFees: 18000,
    averagePackage: 10.4,
    highestPackage: 20,
    placementRate: 93,
    popularCourse: "MBBS",
    description: "Thanjavur Medical College is a historic medical institute in the Delta region. Operating since 1959, it hosts extensive labs, hostels, and operates a major government teaching hospital with huge clinical diversity.",
    logo: "https://images.unsplash.com/photo-1562774053-701939374585?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "http://www.tmc.ac.in"
  },
  {
    name: "Government Vellore Medical College",
    slug: "government-vellore-medical-college",
    city: "Vellore",
    district: "Vellore",
    state: "Tamil Nadu",
    address: "Adukkamparai, Vellore – 632011, Tamil Nadu, India",
    collegeType: "Medical",
    ownership: "Government",
    university: "The Tamil Nadu Dr. M.G.R. Medical University, Chennai",
    rating: 4.4,
    reviewCount: 68,
    annualFees: 18000,
    averagePackage: 9.9,
    highestPackage: 18.5,
    placementRate: 91,
    popularCourse: "MBBS",
    description: "Government Vellore Medical College is a state-run medical college in Vellore district at Adukkamparai. It offers standard clinical training and caters to tertiary medical requirements of northern Tamil Nadu.",
    logo: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "http://www.gvmc.ac.in"
  },
  {
    name: "Government Medical College & Hospital, Karur",
    slug: "government-medical-college-hospital-karur",
    city: "Karur",
    district: "Karur",
    state: "Tamil Nadu",
    address: "Sanapiratti, Karur – 639004, Tamil Nadu, India",
    collegeType: "Medical",
    ownership: "Government",
    university: "The Tamil Nadu Dr. M.G.R. Medical University, Chennai",
    rating: 4.3,
    reviewCount: 45,
    annualFees: 18000,
    averagePackage: 9.5,
    highestPackage: 17.5,
    placementRate: 90,
    popularCourse: "MBBS",
    description: "Government Medical College & Hospital, Karur is a modern state-run medical institution providing comprehensive educational classrooms, advanced clinical labs, and an active district general hospital.",
    logo: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=120&auto=format&fit=crop&q=60",
    coverImage: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=800&auto=format&fit=crop&q=60",
    officialWebsite: "http://www.gmckarur.org"
  }
];

async function main() {
  console.log("Start seeding colleges...");
  
  // Add a unique ID and dates to each college
  const dataWithIds = collegesData.map((c, index) => ({
    id: `college-id-${index + 1}`,
    ...c,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }));

  fs.writeFileSync(
    path.join(__dirname, "../src/lib/colleges.json"),
    JSON.stringify(dataWithIds, null, 2)
  );
  console.log("Seeding finished successfully. Wrote to src/lib/colleges.json");
}

main()
  .then(() => {
    process.exit(0);
  })
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });

